site_name: pytest-emoji
site_description: A pytest plugin that adds emojis to your test result report
site_author: Raphael Pierzina

theme: readthedocs

repo_url: https://github.com/hackebrot/pytest-emoji

pages:
- Home: index.md
